export const creditosPorCurso = {
    "COMUNICACIÓN Y LITERATURA I": 3,
    "PRE CÁLCULO": 3,
    "GLOBALIZACIÓN Y REALIDAD NACIONAL": 3,
    "ESTADÍSTICA Y PROBABILIDADES": 3,
    "SISTEMAS OPERATIVOS I": 3,
    "FUNDAMENTOS DE PROGRAMACIÓN": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PERSONALES I": 1,

    "ALGORITMOS Y ESTRUCTURA DE DATOS": 3,
    "CÁLCULO I": 4,
    "INGENIERÍA DE REQUERIMIENTOS": 3,
    "ANÁLISIS DE DATOS I": 3,
    "ARQUITECTURA DEL COMPUTADOR I": 3,
    "BASE DE DATOS": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PROFESIONALES I": 1,

    "ALGEBRA LINEAL I": 3,
    "ÁLGEBRA LINEAL I": 3,
    "CÁLCULO II": 4,
    "PROGRAMACIÓN ORIENTADA A OBJETOS": 3,
    "ADMINISTRACIÓN DE BASE DE DATOS": 3,
    "FÍSICA I": 4,
    "INGENIERÍA DE PROCESOS DE NEGOCIO": 3,
    "INGENIERÍA DE PROCESOS DE NEGOCIOS": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PERSONALES II": 1,

    "MATEMÁTICA DISCRETA": 3,
    "ESTADISTICA INFERENCIAL": 5,
    "ESTADÍSTICA INFERENCIAL": 5,
    "ANÁLISIS Y DISEÑO DE ALGORITMOS": 3,
    "INTELIGENCIA DE NEGOCIOS": 3,
    "INGENIERÍA DE SOFTWARE I": 3,
    "ROBÓTICA": 3,
    "REDES DE COMUNICACIONES": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PROFESIONALES II": 1,

    "GERENCIA PARA INGENIERÍA": 3,
    "INTELIGENCIA ARTIFICIAL": 3,
    "PRUEBA DE SOFTWARE": 3,
    "DESARROLLO DE APLICACIONES WEB": 3,
    "DESARROLLO DE APLICACIONES MÓVILES": 3,
    "DESARROLLO DE SOLUCIONES DE IOT": 3,
    "INGENIERÍA DE SOFTWARE II": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PERSONALES III": 1,
    "ANÁLISIS MULTIVARIADO I": 3,

    "METODOLOGÍA DE LA INVESTIGACIÓN": 3,
    "ETHICAL HACKING Y SEGURIDAD": 3,
    "INTERACCIÓN HUMANO COMPUTADOR": 3,
    "MACHINE LEARNING": 3,
    "DESARROLLO DE VIDEOJUEGOS I": 3,
    "FINANZAS PARA INGENIERÍA": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PROFESIONALES III": 1,
    "ANÁLISIS MULTIVARIADO II": 3,
    "BIG DATA ANALYTICS": 3,
    "INVESTIGACIÓN OPERATIVA I": 4,

    "ÉTICA Y RESPONSABILIDAD AMBIENTAL": 3,
    "CALIDAD DE SOFTWARE": 3,
    "DESARROLLO DE VIDEOJUEGOS II": 3,
    "DISEÑO Y DESARROLLO DE PRODUCTOS DIGITALES": 3,
    "ENTREPRENEURSHIP": 4,
    "ARQUITECTURA DE SOFTWARE": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PERSONALES IV": 1,
    "ANALÍTICA DE LA WEB": 3,
    "COMPUTACIÓN GRÁFICA": 3,
    "MINERÍA DE DATOS": 3,

    "PROJECT MANAGEMENT": 3,
    "COMPUTACIÓN EN LA NUBE": 3,
    "DISEÑO DE PATRONES DE SOFTWARE": 3,
    "DISEÑO Y EVALUACIÓN DE PROYECTOS": 4,
    "PROYECTO STARTUP": 3,
    "DESPLIEGUE DE APLICACIONES": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PROFESIONALES IV": 1,
    "MINERÍA DE DATOS AVANZADO": 3,

    "CAPSTONE PROJECT I": 3,
    "TRABAJO DE TESIS I": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PERSONALES V": 1,

    "TRABAJO DE TESIS II": 3,
    "DEEP LEARNING": 3,
    "TALLER: DESARROLLO DE COMPETENCIAS PROFESIONALES V": 1,

    "ELECTIVO 1": 3,
    "ELECTIVO 2": 3,
    "ELECTIVO 3": 3,
    "ELECTIVO 4": 3,
    "ELECTIVO 5": 3,
    "ELECTIVO 6": 3,
    "ELECTIVO 7": 3,
    "ELECTIVO 8": 3,
    "ELECTIVO 9": 3,
    "ELECTIVO 10": 3,
    "ELECTIVO 11": 3,
    "ELECTIVO INTERNACIONAL 1": 1.5,
    "ELECTIVO INTERNACIONAL 2": 1.5,
};

const creditosMap = new Map(Object.entries(creditosPorCurso));

export const obtenerCreditosCurso = (nombreCurso) => {
    if (!nombreCurso) return 0;

    const nombreNormalizado = nombreCurso
        .toUpperCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .trim();

    if (creditosMap.has(nombreNormalizado)) {
        return creditosMap.get(nombreNormalizado);
    }

    for (const [curso, creditos] of creditosMap) {
        if (curso.includes(nombreNormalizado) || nombreNormalizado.includes(curso)) {
            return creditos;
        }
    }

    return 3;
};
